version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Optionally add reviewers or labels
    # reviewers:
    #   - team-name
